
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.controller.image.repository }}-deployment"
  labels:
    app: {{ .Values.controller.image.repository }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.controller.image.repository }}
  template:
    metadata:
      labels:
        app: {{ .Values.controller.image.repository }}
    spec:
      containers:
      - name: {{ .Values.controller.image.repository }}
        image: nginx:1.7.9
        ports:
        - containerPort: 80
